# Generated by Django 4.0.3 on 2022-04-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liqpay_public_key', models.CharField(blank=True, max_length=255, null=True)),
                ('liqpay_private_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
