# Generated by Django 4.0.3 on 2022-04-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_transaction_sended_to_user_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsetting',
            name='tax_top_up_fixed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='tax_top_up_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='tax_withdrawal_fixed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='tax_withdrawal_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='threshold',
            field=models.FloatField(default=0),
        ),
    ]
