version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn Lotery.wsgi:application --bind 0.0.0.0:8000"
#    command: bash -c "./manage.py runserver"
    container_name: web_python
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  channels:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    container_name: channels_python
    command: >
      sh -c "daphne -b 0.0.0.0 -p 9001 Lotery.asgi:application"
    ports:
      - 9001:9001
    env_file:
      - ./.env.prod
    depends_on:
      - db


#  daphne:
#    restart: always
#    image: "app_lottery:latest"
#    command: >
#      sh -c "python manage.py collectstatic --noinput &&
#             python manage.py migrate &&
#             daphne -b 0.0.0.0 -p 8001 Lotery.asgi:application"
#    volumes:
#      - static_volume:/home/app/web/static
#      - media_volume:/home/app/web/media
#    container_name: daphne_python
#    ports:
#      - 8001:8001
#    env_file:
#      - ./.env.prod
#    depends_on:
#      - redis

  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: db_python
    environment:
      - POSTGRES_USER=root_user
      - POSTGRES_PASSWORD=nq4242DNe343qrnd
      - POSTGRES_DB=lottery

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    container_name: nginx_python
    ports:
      - 80:80
    depends_on:
      - web

  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    container_name: redis_python
    ports:
      - 6379:6379

  celery-worker1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery-worker1
    image: madefire/chordtest
    hostname: worker1
    env_file:
      - ./.env.prod
    command: ['celery', '-A', 'Lotery.celery.app', 'worker', '-l', 'info']
    volumes:
      - ./:/code
      - /etc/localtime:/etc/localtime:ro
    links:
      - redis
    depends_on:
      - redis
      - web


  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery-beat
    image: madefire/chordtest
    hostname: beat
    env_file:
      - ./.env.prod
    command: ['celery', '-A', 'Lotery.celery.app', 'beat', '-l', 'info']
    volumes:
      - ./:/code
      - /etc/localtime:/etc/localtime:ro
    links:
      - redis
    depends_on:
      - redis
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: