# Generated by Django 4.0.3 on 2022-03-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('playing', 'Playing'), ('lose', 'Lose'), ('win', 'Win')], default='playing', max_length=7),
        ),
    ]
