# Generated by Django 4.0.3 on 2022-04-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_rating_complain'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
