# Generated by Django 4.0.3 on 2022-04-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0010_remove_rating_ratinger_remove_rating_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=255)),
                ('text', models.TextField()),
            ],
        ),
    ]
