# Generated by Django 4.0.3 on 2022-04-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_address_profile_facebook_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='complaints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
