# Generated by Django 4.0.3 on 2022-04-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_profile_count_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating_sum',
            field=models.FloatField(default=0.0),
        ),
    ]
