# Generated by Django 4.0.3 on 2022-04-24 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_message_body_delete_messagebody'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomuser',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomUser',
        ),
    ]
