# Generated by Django 4.0.3 on 2022-04-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_roomuser_room_remove_roomuser_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='coins',
            field=models.FloatField(default=0),
        ),
    ]
